---
# Check current preps
- import_tasks: preflight.yml
  tags:
    - always

# Set Parameters
- name: Define postgres_exporter_system_user
  set_fact:
    postgres_exporter_system_user: "{{ _postgres_exporter_system_user }}"
  when: postgres_exporter_system_user is not defined

- name: Define postgres_exporter_system_group
  set_fact:
    postgres_exporter_system_group: "{{ _postgres_exporter_system_group }}"
  when: postgres_exporter_system_group is not defined

# Install postgres_exporter
- import_tasks: install.yml
  become: true
  when:
    ( not _postgres_exporter_is_installed.stat.exists ) or 
    ( postgres_exporter_install_dir | length > 0 )

- import_tasks: configure.yml
  become: true
  tags:
    - postgres_exporter_configure