---
- name: Assert the usage of systemd
  assert:
    that: ansible_service_mgr == 'systemd'
    msg: "This role only works with systemd"

- name: Check if postgres_exporter is installed
  stat:
    path: "{{ _postgres_exporter_binary }}"
  register: _postgres_exporter_is_installed
  check_mode: false

- name: Get currently installed postgres_exporter version
  command: "{{ _postgres_exporter_binary }} --version"
  args:
    warn: false
  changed_when: false
  register: _r_postgres_exporter_current_version
  when: _postgres_exporter_is_installed.stat.exists

- block:
    - name: Get checksum
      set_fact:
        _checksums: "{{ lookup('url', '{{ postgres_exporter_base_url }}/v' + postgres_exporter_version + '/sha256sums.txt', wantlist=True) | list }}"
      run_once: true

    - name: "Get checksum for {{ go_architecture }} architecture"
      set_fact:
        postgres_exporter_checksum: "{{ item.split(' ')[0] }}"
      with_items: "{{ _checksums }}"
      when:
        - "('linux-' + go_architecture + '.tar.gz') in item"
  delegate_to: localhost
  when: postgres_exporter_install_dir | length == 0